# install with conda env create -f environment.yml
name: 'end-use'
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - altair
  - pandas
  - scikit-learn
  - numpy
  - vl-convert-python
  - ipykernel